START TRANSACTION;

CREATE TABLE "Authors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Authors" PRIMARY KEY ("Id")
);

CREATE TABLE "OrdersAddresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "City" text NOT NULL,
    "Neighborhood" text NOT NULL,
    "Street" text NOT NULL,
    "BuildingNumber" integer NOT NULL,
    "FlatNumber" integer NOT NULL,
    CONSTRAINT "PK_OrdersAddresses" PRIMARY KEY ("Id")
);

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Isbn" text NOT NULL,
    "AuthorId" integer NOT NULL,
    "Price" numeric NOT NULL,
    "RatersCount" real NOT NULL DEFAULT 0,
    "RatingSum" real NOT NULL DEFAULT 0,
    "IsUsed" boolean NOT NULL DEFAULT FALSE,
    "Description" text NOT NULL,
    "Language" smallint NOT NULL,
    "PublishDate" timestamp with time zone NOT NULL,
    "Genre" smallint NOT NULL,
    "Stock" integer NOT NULL,
    "Sold" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Books_CK_Book_RatersCount" CHECK ("RatersCount" >= 0),
    CONSTRAINT "CK_Books_CK_Book_RatingSum" CHECK ("RatingSum" >= 0),
    CONSTRAINT "CK_Books_CK_Book_Sold" CHECK ("Sold" >= 0),
    CONSTRAINT "CK_Books_CK_Book_Stock" CHECK ("Stock" >= 0),
    CONSTRAINT "FK_Books_Authors_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Authors" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Token" text NULL,
    "Name" text NOT NULL,
    "Phone" text NOT NULL,
    "AddressId" integer NOT NULL,
    "Role" smallint NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_OrdersAddresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "OrdersAddresses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BooksReviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Content" text NOT NULL,
    CONSTRAINT "PK_BooksReviews" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_BooksReviews_CK_BookReview_Rating" CHECK ("Rating" >= 0 AND "Rating" <= 5),
    CONSTRAINT "FK_BooksReviews_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BooksReviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CartsItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "BookId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_CartsItems" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_CartsItems_CK_CartItem_Quantity" CHECK ("Quantity" >= 1),
    CONSTRAINT "FK_CartsItems_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartsItems_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "ShippingAddressId" integer NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    "Total" numeric NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Orders_CK_Order_Total" CHECK ("Total" > 0),
    CONSTRAINT "FK_Orders_OrdersAddresses_ShippingAddressId" FOREIGN KEY ("ShippingAddressId") REFERENCES "OrdersAddresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WhishListItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" integer NOT NULL,
    "BookId" integer NOT NULL,
    CONSTRAINT "PK_WhishListItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WhishListItems_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WhishListItems_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrdersItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "BookId" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    CONSTRAINT "PK_OrdersItems" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_OrdersItems_CK_OrderItem_UnitPrice" CHECK ("UnitPrice" > 0),
    CONSTRAINT "FK_OrdersItems_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrdersItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Books_AuthorId" ON "Books" ("AuthorId");

CREATE INDEX "IX_BooksReviews_BookId" ON "BooksReviews" ("BookId");

CREATE INDEX "IX_BooksReviews_UserId" ON "BooksReviews" ("UserId");

CREATE INDEX "IX_CartsItems_BookId" ON "CartsItems" ("BookId");

CREATE INDEX "IX_CartsItems_CustomerId" ON "CartsItems" ("CustomerId");

CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");

CREATE UNIQUE INDEX "IX_Orders_ShippingAddressId" ON "Orders" ("ShippingAddressId");

CREATE INDEX "IX_OrdersItems_BookId" ON "OrdersItems" ("BookId");

CREATE INDEX "IX_OrdersItems_OrderId" ON "OrdersItems" ("OrderId");

CREATE UNIQUE INDEX "IX_Users_AddressId" ON "Users" ("AddressId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE INDEX "IX_WhishListItems_BookId" ON "WhishListItems" ("BookId");

CREATE INDEX "IX_WhishListItems_CustomerId" ON "WhishListItems" ("CustomerId");


COMMIT;